# 本文件采用 TOML 格式 https://toml.io/
# 以下项目的含义及其填写方法详见 https://github.com/ahui2016/R2-Gallery

author = '{{data.author}}'

notes = '''
{{data.notes}}
'''

story = '''
{{data.story}}
'''

frontpage = '{{data.frontpage}}'

albums = [
{% for album in data.albums %}
    '''{{album}}''',
{%- endfor %}
]

checksum = '{{data.checksum}}'

r2_html = '{{data.r2_html}}'

endpoint_url = '{{data.endpoint_url}}'
aws_access_key_id = '{{data.aws_access_key_id}}'
aws_secret_access_key = '{{data.aws_secret_access_key}}'
bucket_name = '{{data.bucket_name}}'
bucket_url = '{{data.bucket_url}}'
