# 本文件采用 TOML 格式 https://toml.io/
# 以下项目的含义及其填写方法详见 https://github.com/ahui2016/R2-Gallery

author = '{{cfg.author}}'

notes = '''
{{cfg.notes}}
'''

story = '''
{{cfg.story}}
'''

r2_html = '{{cfg.r2_html}}'

checksum = '{{cfg.checksum}}'

frontpage = '{{cfg.frontpage}}'

albums = [
{% for album in cfg.albums %}
    '''{{album}}''',
{% endfor %}
]

endpoint_url = '{{cfg.endpoint_url}}'
aws_access_key_id = '{{cfg.aws_access_key_id}}'
aws_secret_access_key = '{{cfg.aws_secret_access_key}}'
bucket_name = '{{cfg.bucket_name}}'
bucket_url = '{{cfg.bucket_url}}'
