# 本文件采用 TOML 格式 https://toml.io/
# 以下项目的含义及其填写方法详见 https://github.com/ahui2016/R2-Gallery

# 以下标明 '可修改' 的项目可以直接编辑, 未标明的请勿直接编辑.

file_id = '{{data.file_id}}'

# 可修改
notes = '''
{{data.notes}}
'''

# 可修改
story = '''
{{data.story}}
'''

# 可修改
ctime = '{{data.ctime}}'

checksum = '{{data.checksum}}'

r2_url = '{{data.r2_url}}'

r2_html = '{{data.r2_html}}'
